# Site settings
title: Learning to Code
header-img: img/home-bg.png
email: annette.drapalski@gmail.com
copyright_name: apalski
description: > # this means to ignore newlines until "baseurl:"
  One Bit at a Time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  apalski
learn_profile: apalski
email_username: annette.drapalski@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
